Repository Hexae/talesofaradia, pull requests merged in 2025-06, with the labels that each got.

#1 Feature/reformat index html for consistency
  index.html
  js/firemaking.js
Labels: enhancement

#2 Fix logo size in login modal
  index.html
Labels: bug

#3 removed fishing integration in index.html
  public/index.html
Labels: enhancement

#4 Implemented basic fishing
  public/firemaking.js
  public/fishing.js
  public/index.html
Labels: bug, enhancement

#5 Added the following mastery capes
  public/images/mastery_capes/Firemaking_Mastery_Cape.png
  public/images/mastery_capes/Fishing_Mastery_Cape.png
  public/images/mastery_capes/Fletching_Mastery_Cape.png
  public/images/mastery_capes/Mining_Mastery_Cape.png
  public/images/mastery_capes/Woodcutting_Mastery_Cape.png
Labels: enhancement

#7 Feature/index items
  public/icons/cooking/Cooking.png
  public/icons/cooking/Cooking.png:Zone.Identifier
  public/icons/fletching/Fletching.png
  public/icons/fletching/Fletching.png:Zone.Identifier
  public/icons/mining/Mining.png
  public/icons/mining/Mining.png:Zone.Identifier
  public/icons/smithing/Smithing.png
  public/icons/smithing/Smithing.png:Zone.Identifier
  public/images/equipments/Adamantite_Chestplate.png
  public/images/equipments/Adamantite_Chestplate.png:Zone.Identifier
  public/images/equipments/Adamantite_Helmet.png
  public/images/equipments/Adamantite_Helmet.png:Zone.Identifier
  public/images/equipments/Adamantite_Platelegs.png
  public/images/equipments/Adamantite_Platelegs.png:Zone.Identifier
  public/images/equipments/Iron_Chestplate.png
  public/images/equipments/Iron_Chestplate.png:Zone.Identifier
  public/images/equipments/Iron_Helmet.png
  public/images/equipments/Iron_Helmet.png:Zone.Identifier
  public/images/equipments/Iron_Platelegs.png
  public/images/equipments/Iron_Platelegs.png:Zone.Identifier
  public/index.html
Labels: enhancement

#6 CSS reorganized + mobile test + new tabs
  public/index.html
Labels: help wanted

#8 Fix Shop section collapse
  public/index.html
Labels: enhancement

#9 Update inventory view/hide feature with list filtering
  public/index.html
Labels: enhancement
